Update pr-unit-test.yml

diff --git a/.github/workflows/pr-unit-test.yml b/.github/workflows/pr-unit-test.yml
--- a/.github/workflows/pr-unit-test.yml
+++ b/.github/workflows/pr-unit-test.yml
@@ -97,21 +97,22 @@ jobs:
             if [ "$JUSTIFICATION_FOUND" = true ]; then
               echo "Justification provided"
               echo "justification=provided" >> $GITHUB_ENV
-              echo "::set-output name=justification_status::Justification provided for missing tests"
+              echo "All required tests are present or justified."
             else
               echo "Justification not found"
               echo "justification=not found" >> $GITHUB_ENV
-              echo "::set-output name=justification_status::Missing tests and no justification found"
+              echo "##[error]Missing tests and no justification found"
+              exit 1
             fi
           else
             echo "No missing tests"
             echo "missing_tests=false" >> $GITHUB_ENV
-            echo "::set-output name=justification_status::All required tests are present"
+            echo "All required tests are present."
           fi
         else
           echo "Label 'no-tests-needed' found, skipping test check"
           echo "missing_tests=false" >> $GITHUB_ENV
-          echo "::set-output name=justification_status::'no-tests-needed' label found, skipping test check"
+          echo "'no-tests-needed' label found, skipping test check."
         fi
 
     - name: Print Justification Status
